#!/bin/bash

# Función para agregar la ruta al PATH en un archivo
add_to_path() {
    local file="$1"
    if [! grep -q "export PATH=*$GAMES" "$file"]; then
        echo "export PATH=\"\$PATH:$NEW_PATH\"" >> "$file"
        echo "Añadido $NEW_PATH a $file"
    else
        echo "$NEW_PATH ya está en $file"
    fi
}

# Agregar la ruta a Bash
add_to_path "/etc/profile"
add_to_path "/etc/bash.bashrc"

# Agregar la ruta a Zsh
add_to_path "/etc/zsh/zshenv"
add_to_path "/etc/zsh/zshrc"
