#!/bin/bash

apt -y remove gnome-games gnome atril qbitorrent gimp inkscape \
onboard iamgemagik libreoffice libreoffice-base libreoffice-base-core \
libreoffice-common zutty libreoffice-base

apt -y autoremove

apt -y purge libreoffice-base-core libreoffice-base-drivers libreoffice-calc libreoffice-common \
libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk3 libreoffice-help-common \ 
libreoffice-help-en-us libreoffice-impress libreoffice-java-common libreoffice-l10n-es \
libreoffice-math libreoffice-report-builder libreoffice-report-builder-bin \
libreoffice-script-provider-bsh libreoffice-script-provider-js \
libreoffice-script-provider-python libreoffice-sdbc-firebird libreoffice-sdbc-hsqldb \ 
libreoffice-sdbc-mysql libreoffice-sdbc-postgresql libreoffice-style-colibre \
libreoffice-style-elementary libreoffice-writer
